### ISSUE TITLE
Update your plasmovoice version.

### ISSUE THREAD

**Issue by MagmaBro123** [ZipeStudio/TalkingHeads#1]
Title.

![image](https://github.com/user-attachments/assets/2207f798-7825-4f0e-a507-34e7563241c3)

**Comment by ZipeStudio** [comment]
my bad, you need download this PlasmoVoice version for mod
(https://github.com/plasmoapp/plasmo-voice/releases/tag/2.1.0-SNAPSHOT)
Because PlasmoVoice 2.1.0 is currently only at github snapshots.
